name: Suggest an attestation app
description: Suggest an attestation app for developers to use when building with Optimism
title: "[ATT] Add PR title"
labels: ["documentation,attestation,community-request"]
body:
  - type: markdown
    attributes:
      value: |
        Before submitting this suggestion, be sure to read the [listing of current attestation apps](https://docs.metall2.com/identity/applications).
  - type: markdown
    id: project_info
    attributes:
      value: "## Project Info"
  - type: input
    id: att_name
    attributes:
      label: Attestation App Name
    validations:
      required: true
  - type: textarea
    id: att_description
    attributes:
      label: Attestation App Description
    validations:
      required: true
  - type: input
    id: att_URL
    attributes:
      label: Attestation App URL
      description: Please provide the URL for us to link in the project description above.
    validations:
      required: true
  - type: input
    id: att_live_date
    attributes:
      label: When did the product go live?
      description: We prioritize products that are battle-tested.
    validations:
      required: true
  - type: dropdown
    id: att_open_source
    attributes:
      label: Is the product open source?
      description: We prioritize open source projects when possible.
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: input
    id: att_github
    attributes:
      label: GitHub URL
      description: If the project is open source, please provide a link to the product's repo.
  - type: textarea
    id: att_additional_context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the product here.
